# Write your MySQL query statement below
SELECT RES.PROJECT_ID , ROUND(AVG(RES.EXPERIENCE_YEARS),2) AS average_years  
FROM (SELECT P.PROJECT_ID, E.EXPERIENCE_YEARS FROM 
PROJECT P, EMPLOYEE E WHERE E.EMPLOYEE_ID = P.EMPLOYEE_ID ) RES
GROUP BY RES.PROJECT_ID